Bump GitHub action versions in reusable_testing.yml
tarantool/go-tarantool pull request #308
Opened 2023-06-26 15:29 UTC by i-cod

- actions/checkout: v2 -> v3
- actions/download-artifact: v2 -> v3

2023-06-26 18:18 UTC, oleg-jukovec requested changes
Thank you for the patch! Please, change the commit message to:

`ci: bump GitHub action versions in reusable_testing.yml`

the change will help make the commit message in the same style as other commits.

2023-06-27 11:06 UTC, better0fdead approved these changes

2023-06-27 13:07 UTC, ylobankov approved these changes

2023-06-27 13:13 UTC, oleg-jukovec approved these changes

2023-06-27 13:13 UTC, merged