pool: implemented Role Stringer interface
tarantool/go-tarantool pull request #406
Opened 2024-09-04 06:58 UTC by KaymeKaydex

implemented Role Stringer interface for human-readable printing

Related issues: #405

2024-09-04 07:25 UTC, oleg-jukovec commented
I suggest to use `stringer` + `go generate` instead of a custom code.
```
diff --git a/pool/const.go b/pool/const.go
index 7ec239f..22bff4f 100644
--- a/pool/const.go
+++ b/pool/const.go
@@ -30,8 +30,12 @@ const (
 // Role describes a role of an instance by its mode.
 type Role uint32
 
+//go:generate stringer -type Role -linecomment
 const (
-    UnknownRole Role = iota // A connection pool failed to discover mode of the instance.
-    MasterRole              // The instance is read-write mode.
-    ReplicaRole             // The instance is in read-only mode.
+    // A connection pool failed to discover mode of the instance.
+    UnknownRole Role = iota // unknown
+    // The instance is read-write mode.
+    MasterRole              // master
+    // The instance is in read-only mode.
+    ReplicaRole             // replica
 )
 ```

2024-09-04 07:27 UTC, oleg-jukovec commented on pool/const_test.go
> +	require.True(t, len(fmt.Sprintf("%v", ReplicaRole)) > 1)
Let's compare real values ​​instead of the existence check.

2024-09-05 10:22 UTC, KaymeKaydex commented
@oleg-jukovec i generated Stringer face by stringer library. since it can only cut prefixes, I was forced to rename the roles, since they are not specified externally, this will not change the user interface

2024-09-05 15:16 UTC, oleg-jukovec commented
> @oleg-jukovec i generated Stringer face by stringer library. since it can only cut prefixes, I was forced to rename the roles, since they are not specified externally, this will not change the user interface

Unfortunately, we could not change naming because it will break backward compatibility.

But the ‘stringer’ could generate custom strings, see ‘-linecoment’ option for the ‘stringer’ and my patch more carefully.

2024-09-09 09:56 UTC, oleg-jukovec commented on pool/const_test.go
> +	require.Equal(t, "replica", ReplicaRole)
```suggestion
	require.Equal(t, "unknown", UnknownRole.String())
	require.Equal(t, "master", MasterRole.String())
	require.Equal(t, "replica", ReplicaRole.String())
```

2024-09-09 09:56 UTC, oleg-jukovec requested changes
Please, fix red tests.

2024-09-09 15:51 UTC, oleg-jukovec approved these changes

2024-09-09 15:52 UTC, DerekBum reviewed
Thank you for the patch! Please see couple of nits below.

Also, don't forget to squash the commits after the work is done. And please change the line `Related issues: #405` to the `Closes #405`, so the issue could be closed automatically after the merge.

2024-09-14 21:13 UTC, KaymeKaydex commented
@DerekBum thanks, I accepted the proposed changes and squashed them

2024-09-15 13:59 UTC, DerekBum approved these changes
Thanks for the patch!

2024-09-16 13:21 UTC, merged