Added logic for working with Tarantool schema via Box
tarantool/go-tarantool pull request #426
Opened 2024-12-27 17:17 UTC by KaymeKaydex

- Implemented the `box.Schema()` method that returns a `Schema` object for schema-related operations

What has been done? Why? What problem is being solved?

I didn't forget about (remove if it is not applicable):

- [ ] Tests (see [documentation](https://pkg.go.dev/testing) for a testing package)
- [ ] Changelog (see [documentation](https://keepachangelog.com/en/1.0.0/) for changelog format)
- [ ] Documentation (see [documentation](https://go.dev/blog/godoc) for documentation style guide)

Related issues:

2024-12-29 00:03 UTC, oleg-jukovec commented on box/schema_user.go
> +}
The same about a constructor as for the `Schema` type.

2024-12-29 00:03 UTC, oleg-jukovec commented on box/schema_user.go
Please, add unit-test for requests and responses types in the file.

We probably also need to think about naming and location of requests types in this package. As example, at now some requests are at `request.go` file. It could be confusing.

There are two ways I see:
1. We could locate all requests/responses into the `request.go` file (I don't like the idea).
2. We need move types from `request.go` into a proper files in the same manner as for the current ones.

2025-01-10 09:30 UTC, KaymeKaydex commented on box/schema.go
> +}
done

2025-01-10 09:31 UTC, KaymeKaydex commented on box/box_test.go
> -
done

2025-01-10 09:33 UTC, KaymeKaydex commented on box/schema.go
> +}
done

2025-01-10 09:36 UTC, KaymeKaydex commented on box/schema_user.go
> +}
done

2025-01-10 09:39 UTC, KaymeKaydex commented on box/schema_user.go
I propose to completely get rid of request.go since baseRequest is implemented incorrectly, the Info call is a simple CallRequest, which should inherit all the logic from a regular call request, as is done for schema user

2025-01-10 09:45 UTC, KaymeKaydex commented on box/schema_user.go
All box requests are not custom requests with msgpack, thats why we need to use just simple call requests

2025-01-10 10:48 UTC, KaymeKaydex commented on box/tarantool_test.go
> +}
done

2025-01-10 10:57 UTC, KaymeKaydex commented on box/tarantool_test.go
> +}
i wrote some sub-tests, that looks better

2025-01-15 11:24 UTC, oleg-jukovec requested changes
Please, add more unit-tests for a new requests/response. You could see how it is tested on the main package and inside the `crud` subpackage.

We also need examples (in example_test.go) with new features. This will help users to use the library.

Finally, we need to keep a backward compatibility until a next major release, so we need to add another Info() method with a context instead of changing the current one.

2025-01-15 11:24 UTC, oleg-jukovec commented on CHANGELOG.md
> +- Box Info method now requires context and implements CallRequest type instead custom baseRequest.
This is a breaking change. We need an another method and keep a backward compatibility here. You could create an issue to delete an old method in the next major release.

2025-01-20 18:53 UTC, KaymeKaydex commented on CHANGELOG.md
> +- Box Info method now requires context and implements CallRequest type instead custom baseRequest.
Removed

2025-01-21 15:16 UTC, KaymeKaydex commented
> Please, add more unit-tests for a new requests/response. You could see how it is tested on the main package and inside the `crud` subpackage.
> 
> We also need examples (in example_test.go) with new features. This will help users to use the library.
> 
> Finally, we need to keep a backward compatibility until a next major release, so we need to add another Info() method with a context instead of changing the current one.

i removed interface changes
added new examples for new methods
and added more tests to make coverage up, now all methods are covered

2025-01-23 15:58 UTC, oleg-jukovec reviewed
Please, fix the commit message:


```
box: ddded logic for working with Tarantool schema

Implemented the `box.Schema()` method that returns a `Schema`
object for schema-related operations
```

2025-01-23 15:58 UTC, oleg-jukovec commented on CHANGELOG.md
> +- Implemented box.session.su request and sugar interface only for current session granting.
```suggestion
- Implemented box.session.su request and sugar interface only for current session granting (#426).
```

2025-01-23 15:58 UTC, oleg-jukovec commented on box/example_test.go
> +	fmt.Printf("Current exists state: %+v\n", exists)
Why all the examples are not runable as tests? You can run tarantula before running the example as it is done in other tests.

```suggestion
	fmt.Printf("Box schema users exists are equal")
	fmt.Printf("Current exists state: %+v\n", exists)

	// Output:
	// Box schema users exists are equal
	// Current exists state: true
```

2025-01-23 15:58 UTC, oleg-jukovec commented on box/example_test.go
> +	// Connect to Tarantool
You add the comment in some tests, but not to another. It is a little confusing.
```suggestion
	// Connect to Tarantool.
```

2025-01-23 15:58 UTC, oleg-jukovec commented on box/example_test.go
> +	// Create a new user
```suggestion
	// Create SchemaUser.
	schemaUser := box.NewSchemaUser(client)

	// Create a new user.
```

2025-01-23 15:58 UTC, oleg-jukovec commented on box/example_test.go
> +	// Connect to Tarantool
The same about dots: a comment should end with a dot. Please fix all comments in the file.

2025-01-23 15:58 UTC, oleg-jukovec commented on box/schema_test.go
> +	require.NotNil(t, b)
```suggestion
	require.NotNil(t, b)
	require.Nil(t, b.User())
```

2025-01-23 15:58 UTC, oleg-jukovec commented on box/schema_test.go
> +func TestNewSchema(t *testing.T) {
You could probably add a unit-test that a Schema.User() returns a SchemaUser object with the given doer (with a mock doer). Something like:
```
doer := struct{
    tarantool.Doer
}{}
require.Equal(*NewSchema(doer).User(), *NewSchemUser(doer))
```

2025-01-23 15:58 UTC, oleg-jukovec commented on box/schema_user.go
> +	PrivilegeObjectTypeUniverse PrivilegeObjectType = "universe"
Can we use this naming?

```suggestion
// https://www.tarantool.io/en/doc/latest/admin/access_control/#all-object-types-and-permissions
type PrivilegeType string

const (
	// PrivilegeUniverse - privilege type based on universe.
	// A database (box.schema) that contains database objects, including spaces,
	// indexes, users, roles, sequences, and functions.
	// Granting privileges to universe gives a user access to any object in the database.
	PrivilegeUniverse PrivilegeType = "universe"
```

2025-01-23 15:58 UTC, oleg-jukovec commented on box/schema_user.go
> +	ObjectName string
And such...
```suggestion
	// Type - one of privilege object types (it might be space,function, etc.).
	Type PrivilegeObjectType
	// Name - can be the name of a function or space,
	// and can also be empty in case of universe access
	Name string
```

2025-01-23 15:58 UTC, oleg-jukovec commented on box/tarantool_test.go
> +	// Create new user
Please, checkk all comments for dots )
```suggestion
	// Create new user.
```

2025-01-25 09:59 UTC, KaymeKaydex commented on box/schema_user.go
> +	ObjectName string
Naming based on tarantool doc https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_schema/user_grant/#lua-function.box.schema.user.grant

2025-01-28 18:38 UTC, KaymeKaydex commented on box/schema_user.go
> +	PrivilegeObjectTypeUniverse PrivilegeObjectType = "universe"
fixed

2025-01-28 18:42 UTC, KaymeKaydex commented on box/schema_test.go
> +	require.NotNil(t, b)
it might be not nil, cause we panics only on nil connection

2025-01-28 18:45 UTC, KaymeKaydex commented on box/schema_test.go
> +	require.NotNil(t, b)
i added test with info method call panics, cause conn is nil

i think resolved

2025-01-28 18:45 UTC, KaymeKaydex commented on box/example_test.go
> +	// Connect to Tarantool
fixed

2025-01-28 18:57 UTC, KaymeKaydex commented on box/schema_test.go
> +func TestNewSchema(t *testing.T) {
i added such test for schema 

fixed

2025-01-28 19:00 UTC, KaymeKaydex commented on box/schema_user.go
> +	ObjectName string
fixed

2025-01-28 20:23 UTC, KaymeKaydex commented on box/example_test.go
> +	fmt.Printf("Current exists state: %+v\n", exists)
fixed

2025-01-28 20:24 UTC, KaymeKaydex commented
> Please, fix the commit message:
> 
> ```
> box: ddded logic for working with Tarantool schema
> 
> Implemented the `box.Schema()` method that returns a `Schema`
> object for schema-related operations
> ```

done

2025-02-04 16:04 UTC, oleg-jukovec approved these changes

2025-02-05 07:48 UTC, oleg-jukovec requested changes

2025-02-05 07:48 UTC, oleg-jukovec commented on box/schema_test.go
> +	t.Run("nil conn panics", func(t *testing.T) {
Please, split it into 3 separate tests.

2025-02-05 07:48 UTC, oleg-jukovec commented on box/tarantool_test.go
> +	t.Run("create user already exists error", func(t *testing.T) {
The same, please, split it into separate tests instead of the nesting.

2025-02-05 07:48 UTC, oleg-jukovec commented on box/tarantool_test.go
> +	t.Run("drop user after create", func(t *testing.T) {
etc

2025-02-05 07:48 UTC, oleg-jukovec commented on box/tarantool_test.go
> +	t.Run("user not found", func(t *testing.T) {
etc

2025-02-05 07:48 UTC, oleg-jukovec commented on box/tarantool_test.go
> +	t.Run("test user privileges is correct", func(t *testing.T) {
etc

2025-02-05 07:48 UTC, oleg-jukovec commented on box/tarantool_test.go
> +	t.Run("can`t grant without su permissions", func(t *testing.T) {
etc

2025-02-05 07:48 UTC, oleg-jukovec commented on box/tarantool_test.go
> +	t.Run("can`t revoke without su permissions", func(t *testing.T) {
etc

2025-02-05 07:48 UTC, oleg-jukovec commented on box/tarantool_test.go
> +	t.Run("su with call", func(t *testing.T) {
etc

2025-04-16 09:52 UTC, KaymeKaydex commented on box/schema_test.go
> +	t.Run("nil conn panics", func(t *testing.T) {
done

2025-04-16 09:53 UTC, KaymeKaydex commented on box/tarantool_test.go
> +	t.Run("drop user after create", func(t *testing.T) {
done

2025-04-16 09:53 UTC, KaymeKaydex commented on box/tarantool_test.go
> +	t.Run("can`t revoke without su permissions", func(t *testing.T) {
done

2025-04-16 09:53 UTC, KaymeKaydex commented on box/tarantool_test.go
> +	t.Run("su with call", func(t *testing.T) {
done

2025-04-16 09:53 UTC, KaymeKaydex commented on box/tarantool_test.go
> +	t.Run("can`t grant without su permissions", func(t *testing.T) {
done

2025-05-07 09:59 UTC, KaymeKaydex commented
@oleg-jukovec @DerekBum @themilchenko up

2025-05-25 17:52 UTC, oleg-jukovec approved these changes
Thanks for the patch. It would be nice if @dmyger paid attention to the test coverage.

2025-05-25 17:52 UTC, oleg-jukovec commented on box/box.go
> +}
It would be nice to write a test that checks whether the created circuit uses the connection passed to `box.New`.

2025-05-30 11:06 UTC, dmyger approved these changes

2025-06-20 10:23 UTC, oleg-jukovec requested changes
See comments above.

2025-06-27 13:03 UTC, oleg-jukovec commented
Thank you for the PR! We've added some minor fixes and merged it: https://github.com/tarantool/go-tarantool/pull/446

2025-06-27 13:03 UTC, closed without merging